release:
        only:
                - master
        script:
                - mkdir build || true
                - cd build
                - cmake -DCMAKE_BUILD_TYPE=Release ..
                - cmake --build .
                - cmake --build . --target checks
                - mv circle ..
        cache:
                key: "$CI_BUILD_REF_NAME/Release"
                untracked: true
                paths:
                        - build/
        artifacts:
                name: "circle-release"
                paths:
                        - circle
                expire_in: 1 week
        tags:
                - builder


debug:
        script:
                - mkdir build || true
                - cd build
                - cmake -DCMAKE_BUILD_TYPE=Debug ..
                - cmake --build .
                - cmake --build . --target checks
                - mv circle ..
        cache:
                key: "$CI_BUILD_REF_NAME/Debug"
                untracked: true
                paths:
                        - build/
        artifacts:
                name: "circle-debug"
                paths:
                        - circle
                expire_in: 1 week
        tags:
                - builder

deploy-debug:
        stage: deploy
        script:
                - echo "Deploying debug build..."
        dependencies:
                - debug
        script:
                - pwd
                - cp -a circle ${BYLINS_DEBUG_HOME}
                - touch ${BYLINS_DEBUG_HOME}/touch.me.for.reboot
        when: manual
        tags:
                - mirror

deploy-release:
        only:
                - master
        stage: deploy
        script:
                - echo "Deploying release build..."
        dependencies:
                - release
        script:
                - cp -a circle ${BYLINS_RELEASE_HOME}
                - touch ${BYLINS_RELEASE_HOME}/touch.me.for.reboot
        when: manual
        tags:
                - mirror
