stages:
        - build
        - checks

release:build:
        only:
            - master
        script:
                - mkdir build
                - cd build
                - cmake -DCMAKE_BUILD_TYPE=Release ..
                - cmake --build .
        stage: build
        cache:
                key: "$CI_BUILD_ID/$CI_PIPELINE_ID"
                untracked: true
                paths:
                        - build/
        artifacts:
            name: "circle-release"
            paths:
                - build/circle
            when: on_success
            expire_in: 1 week


release:checks:
        script:
                - cmake --build build --target checks
        stage: checks
        cache:
                key: "$CI_BUILD_ID/$CI_PIPELINE_ID"
                untracked: true
                paths:
                        - build/
        only:
            - master

debug:build:
        script:
                - mkdir build
                - cd build
                - cmake -DCMAKE_BUILD_TYPE=Debug ..
                - cmake --build .
        stage: build
        cache:
                key: "$CI_BUILD_ID/$CI_PIPELINE_ID"
                untracked: true
                paths:
                        - build/

        artifacts:
            name: "circle-debug"
            paths:
                - build/circle
            when: on_success
            expire_in: 1 week

debug:checks:
        script:
                - cmake --build build --target checks
        stage: checks
        cache:
                key: "$CI_BUILD_ID/$CI_PIPELINE_ID"
                untracked: true
                paths:
                        - build/
