release:
        only:
                - master
        script:
                - mkdir build
                - cd build
                - cmake -DCMAKE_BUILD_TYPE=Release ..
                - cmake --build .
                - cmake --build . --target checks
                - gzip -c circle > circle-release.gz
        cache:
                key: "$CI_BUILD_REF_NAME/Release"
                untracked: true
                paths:
                        - build/
        artifacts:
                name: "circle-release.gz"
                paths:
                        - build/circle
                expire_in: 1 week


debug:
        script:
                - mkdir build
                - cd build
                - cmake -DCMAKE_BUILD_TYPE=Debug ..
                - cmake --build .
                - cmake --build . --target checks
                - gzip -c circle > circle-debug.gz
        cache:
                key: "$CI_BUILD_REF_NAME/Debug"
                untracked: true
                paths:
                        - build/

        artifacts:
                name: "circle-debug.gz"
                paths:
                        - build/circle
                expire_in: 1 week
