release:
        only:
                - master
        script:
                - mkdir build || true
                - cd build
                - cmake -DCMAKE_BUILD_TYPE=Release ..
                - cmake --build .
                - cmake --build . --target checks
                - mv circle ..
        cache:
                key: "$CI_BUILD_REF_NAME/Release"
                untracked: true
                paths:
                        - build/
        artifacts:
                name: "circle-release"
                paths:
                        - circle
                expire_in: 1 week


debug:
        script:
                - mkdir build || true
                - cd build
                - cmake -DCMAKE_BUILD_TYPE=Debug ..
                - cmake --build .
                - cmake --build . --target checks
                - mv circle ..
        cache:
                key: "$CI_BUILD_REF_NAME/Debug"
                untracked: true
                paths:
                        - build/
        artifacts:
                name: "circle-debug"
                paths:
                        - circle
                expire_in: 1 week

deploy-to-mirror:
        stage: deploy
        script:
                - echo "Deploying into mirror"
        tags:
                - mirror
        when: manual
