stages:
        - build
        - checks

release:
        only:
                - master
        script:
                - mkdir build
                - cd build
                - cmake -DCMAKE_BUILD_TYPE=Release ..
                - cmake --build .
                - cmake --build . --target checks
        stage: build
        cache:
                key: "$CI_BUILD_REF_NAME/Release"
                untracked: true
                paths:
                        - build/
        artifacts:
                name: "circle-release"
                paths:
                        - build/circle
                when: on_success
                expire_in: 1 week


debug:
        script:
                - mkdir build
                - cd build
                - cmake -DCMAKE_BUILD_TYPE=Debug ..
                - cmake --build .
                - cmake --build . --target checks
        stage: build
        cache:
                key: "$CI_BUILD_REF_NAME/Debug"
                untracked: true
                paths:
                        - build/

        artifacts:
                name: "circle-debug"
                paths:
                        - build/circle
                when: on_success
                expire_in: 1 week
