stages:
        - generate
        - build
        - checks

cache:
        key: $CI_BUILD_REF_NAME
        untracked: true
        paths:
                - build/

generate:
        script:
                - mkdir build || true
                - cd build
                - cmake ..
        stage: generate

build:
        script:
                - cmake --build build
        stage: build
        artifacts:
            name: "circle"
            paths: build/circle
            when: on_success
            expire_in: 1 week

check:
        script:
                - cmake --build build --target checks
        stage: checks
