release:
        only:
                - master
        script:
                - mkdir build || true
                - cd build
                - cmake -DCMAKE_BUILD_TYPE=Release ..
                - cmake --build .
                - cmake --build . --target checks
                - mv circle ..
                - iconv -f utf8 -t koi8-r changelog > ../changelog
        cache:
                key: "$CI_BUILD_REF_NAME/Release"
                untracked: true
                paths:
                        - build/
        artifacts:
                name: "circle-release"
                paths:
                        - circle
                        - changelog
                expire_in: 1 week

debug:
        script:
                - mkdir build || true
                - cd build
                - cmake -DCMAKE_BUILD_TYPE=Debug ..
                - cmake --build .
                - cmake --build . --target checks
                - mv circle ..
                - iconv -f utf8 -t koi8-r changelog > ../changelog
        cache:
                key: "$CI_BUILD_REF_NAME/Debug"
                untracked: true
                paths:
                        - build/

        artifacts:
                name: "circle-debug"
                paths:
                        - circle
                        - changelog
                expire_in: 1 week
