stages:
        - build
        - checks

build-release:
        only:
            - master
        script:
                - mkdir build || true
                - cd build
                - cmake -DCMAKE_BUILD_TYPE=${CIRCLE_BUILD_TYPE} ..
                - cmake --build build
        stage: build
        cache:
                key: "$CI_BUILD_ID/Release"
                untracked: true
                paths:
                        - build/
        artifacts:
            name: "circle-release"
            paths:
                - build/circle
            when: on_success
            expire_in: 1 week


checks-release:
        script:
                - cmake --build build --target checks
        stage: checks
        cache:
                key: "$CI_BUILD_ID/Release"
                untracked: true
                paths:
                        - build/
        only:
            - master

build-debug:
        script:
                - mkdir build || true
                - cd build
                - cmake -DCMAKE_BUILD_TYPE=Debug ..
                - cmake --build build
        stage: build
        cache:
                key: "$CI_BUILD_ID/Debug"
                untracked: true
                paths:
                        - build/

        artifacts:
            name: "circle-debug"
            paths:
                - build/circle
            when: on_success
            expire_in: 1 week

checks-debug:
        script:
                - cmake --build build --target checks
        stage: checks
        cache:
                key: "$CI_BUILD_ID/Debug"
                untracked: true
                paths:
                        - build/
