stages:
        - generate
        - build
        - checks

generate:
        script:
                - mkdir build
                - cd build
                - cmake ..
        stage: generate

build:
        script:
                - pwd
                - cd build
                - camke --build .
        stage: build

check:
        script:
                - pwd
                - cd build
                - cmake --build . --target checks
        stage: checks
